#!/bin/bash
typeset -i auth=$authenticated
if [ $auth -eq 0 ]
then
	clear
	source ./authenticate.sh
else
clear
echo " "
echo " "
echo "        Welcome to the NOURAN_MOSTAFA_DB "
echo " "
echo " "
dbsPATH=~/bash-project-github/databases
PS3='>'
select x in "Create Database" "List Databases" "Connect to Databases" "Drop Database" "Exit"
do 
	case $x in
		"Create Database") source ./createDB.sh;;
		"List Databases") source ./listDB.sh;;
		"Connect to Databases") source ./connectToDB.sh 0;;
		"Drop Database") source ./dropDB.sh;;
		"Exit") exit;;
		*) echo "ERROR: invalid input, try again"
	esac
done
fi
